import Top from "../../components/top/Top";
import Header from "../../components/header/Header";
import CartContainer from "../../components/cart/CartContainer";
import Footer from "../../components/footer/Footer";
import Head from "next/head";
import {GetServerSideProps} from "next";
import categoryController from "../../controllers/categoryController";
import cityController from "../../controllers/cityController";
import constController from "../../controllers/constController";
import * as React from "react";
import {AddressType, BaseCityType, CategoryType, ProductType, StreetsignColorType} from "../../consts/types";
import addressController from "../../controllers/addressController";
import productController from "../../controllers/productController";

type PropsType = {
    categories: Array<CategoryType>
    cities: BaseCityType[]
    company: any
    products: ProductType[]
    streetsignColors: StreetsignColorType[]
}

export default function CartPage({categories, cities, company, products, streetsignColors}: PropsType) {
    return (
        <>
            <Top cities={cities} company={company}/>
            <div className="main-content-wrapper d-flex clearfix">
                <Header categories={categories} />
                {/*// @ts-ignore*/}
                <CartContainer cities={cities}
                               products={products}
                               streetsignColors={streetsignColors}
                               addresses={[]}
                               step={0} />
                <Footer categories={categories} company={company}/>
            </div>

            <Head>
                <title>Create Next App - Москва</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    const categories = await categoryController.getCategories()
    const cities = await cityController.getCities()
    const company = constController.getCompany()

    const products = await productController.getProducts()
        .then(data => data.filter(el => el.is_published))
    const streetsignColors = constController.getStreetsignColors()

    return {
        props: {
            categories,
            cities,
            company,
            products,
            streetsignColors,
        },
    };
}