import {GetServerSideProps} from 'next'
import Head from 'next/head'
import {BaseCityType, CategoryType, StreetsignColorType, StreetsignType} from "../consts/types";
import * as React from "react";
import Top from "../components/top/Top"
import Header from '../components/header/Header';
import Footer from "../components/footer/Footer";
import ConstructorContainer from "../components/constructor/ConstructorContainer";
import categoryController from "../controllers/categoryController";
import cityController from "../controllers/cityController";
import productController from "../controllers/productController";
import constController from "../controllers/constController";
import faviconImg from "../public/favicon.ico"

type PropsType = {
    error: any,
    categories: Array<CategoryType>
    cities: BaseCityType[]
    company: any
    streetsigns: StreetsignType[]
    streetsignColors: StreetsignColorType[]
}

export default function Home({categories, cities, company, streetsigns, streetsignColors}: PropsType) {
    return (
        <>
            <Top cities={cities} company={company}/>
            <div className="main-content-wrapper d-flex clearfix">
                <Header categories={categories} />
                <ConstructorContainer streetsigns={streetsigns} streetsignColors={streetsignColors} />
                <Footer categories={categories} company={company}/>
            </div>

            <Head>
                <title>Create Next App - Москва</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href={faviconImg.src}/>
            </Head>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    //console.log(typeof context.req)

    const categories = await categoryController.getCategories()
    const cities = await cityController.getCities()
    const company = constController.getCompany()

    const streetsigns = await productController.getStreetsigns()
    const streetsignColors = constController.getStreetsignColors()

    return {
        props: {
            categories: categories,
            cities: cities,
            company: company,
            streetsigns: streetsigns,
            streetsignColors: streetsignColors,
        },
    };
}